#pragma once

#include <Arduino.h>

#include "../LiDAR/LiDARSensor.h"
#include "../driver/MecanumDriver.h"
#include "../driver/RemoteController.h"

namespace debug_print {

/**
 * @brief Record the elapsed time between successive RC updates.
 * @details This feeds the cadence statistics printed by printRcUpdateCadence and keeps the state local to the debug module.
 * @param nowUs Current timestamp in microseconds.
 * @author GitHub Copilot
 * @date 2026-06-03
 */
void noteRcUpdateCadence(uint32_t nowUs);

/**
 * @brief Print a throttled summary of invalid RC drive-signal diagnostics.
 * @param rc Remote controller instance that owns the channel debug snapshots.
 * @param nowMs Current timestamp in milliseconds.
 * @param elapsedMs Elapsed time since the previous control update.
 * @author GitHub Copilot
 * @date 2026-06-03
 */
void printRcDebugSummary(const RemoteController& rc, uint32_t nowMs, uint32_t elapsedMs);

/**
 * @brief Print the aggregated RC update cadence statistics and reset the counters.
 * @author GitHub Copilot
 * @date 2026-06-03
 */
void printRcUpdateCadence();

/**
 * @brief Print the latest LiDAR distances used by the low-rate control loop diagnostics.
 * @param lidarAt0Deg Result of the LiDAR query at 0 degrees.
 * @param lidarAt90Deg Result of the LiDAR query at 90 degrees.
 * @param lidarAt270Deg Result of the LiDAR query at 270 degrees.
 * @author GitHub Copilot
 * @date 2026-06-03
 */
void printLidarDistances(
    const LiDARSensor::QueryResult& lidarAt0Deg,
    const LiDARSensor::QueryResult& lidarAt90Deg,
    const LiDARSensor::QueryResult& lidarAt270Deg);

/**
 * @brief Print a detailed LiDAR scan summary, including scan counters and matched angles.
 * @param lidar Current LiDAR sensor instance.
 * @param lidarAt0Deg Result of the LiDAR query at 0 degrees.
 * @param lidarAt90Deg Result of the LiDAR query at 90 degrees.
 * @param lidarAt270Deg Result of the LiDAR query at 270 degrees.
 * @author GitHub Copilot
 * @date 2026-06-03
 */
void printDetailedLidarDistances(
    const LiDARSensor& lidar,
    const LiDARSensor::QueryResult& lidarAt0Deg,
    const LiDARSensor::QueryResult& lidarAt90Deg,
    const LiDARSensor::QueryResult& lidarAt270Deg);

/**
 * @brief Print the RC drive-channel joystick values and pulse widths.
 * @param rc Remote controller instance used for the snapshot.
 * @author GitHub Copilot
 * @date 2026-06-03
 */
void printDriveRcSnapshot(const RemoteController& rc);

/**
 * @brief Print the scaled wheel commands currently sent to the mecanum driver.
 * @param frontLeftCommand Front-left wheel command after scaling.
 * @param frontRightCommand Front-right wheel command after scaling.
 * @param rearLeftCommand Rear-left wheel command after scaling.
 * @param rearRightCommand Rear-right wheel command after scaling.
 * @author GitHub Copilot
 * @date 2026-06-03
 */
void printScaledWheelCommands(float frontLeftCommand, float frontRightCommand, float rearLeftCommand, float rearRightCommand);

/**
 * @brief Print the raw wheel commands generated by the mecanum mixer.
 * @param wheelCommands Mixed wheel commands before scaling.
 * @author GitHub Copilot
 * @date 2026-06-03
 */
void printTargetWheelCommands(const MecanumDriver::WheelCommands& wheelCommands);

}  // namespace debug_print